# Generated by Django 5.0.3 on 2024-03-27 07:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0002_alter_server_member"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="catergory",
            new_name="category",
        ),
        migrations.AlterField(
            model_name="server",
            name="member",
            field=models.ManyToManyField(
                blank=True, related_name="server_member", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
