# Generated by Django 5.0.3 on 2024-04-09 08:57

import server.models
import server.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("server", "0006_alter_category_icon_alter_server_banner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=server.models.category_icon_upload_path,
                validators=[server.validators.validate_svg_file_extension],
            ),
        ),
    ]
